name: Website For 50
favicon: null
layout_spectrum: 0.4721910860389471
typography_spectrum: 0.27717644814401865
title: Website For $50
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.966938623227179
  lightness: 0.8659924222156405
  saturation: 0.35969922645017505
  rhythmicContrast: 0.9561363407410681
purpose: []
