name: Website For 50
favicon: null
layout_spectrum: 0.10856
typography_spectrum: 0.85394
title: Website For $50
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#36404a'
    - '#f47e10'
    - '#ea5209'
    - '#f7be26'
  brandStrength: 0.966938623227179
  lightness: 0.8659924222156405
  saturation: 0.35969922645017505
  rhythmicContrast: 0.9561363407410681
purpose: []
